name: Pynocchio Lint
on: [push, pull_request]

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]
        poetry-version: ["1.5"]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Run image
      uses: abatilo/actions-poetry@v2
      with:
        poetry-version: ${{ matrix.poetry-version }}
    - name: Install dependencies
      run: poetry install
    - name: Run black
      run: poetry run black --check spycular
    - name: Run isort
      run: poetry run isort -c spycular
    - name: Run flake8
      run: poetry run flake8 --count spycular
    - name: Run MyPy
      run: poetry run mypy spycular
    - name: Run Docformatter
      run: poetry run docformatter --check --wrap-summaries 72 --wrap-descriptions 79 --recursive spycular
