name: Spycular Unit Tests
on: [push, pull_request]

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]
        poetry-version: ["1.5"]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Run image
      uses: abatilo/actions-poetry@v2
      with:
        poetry-version: ${{ matrix.poetry-version }}
    - name: Install dependencies
      run: poetry install -E capnp -E numpy -E torch -E websocket
    - name: Run unit tests
      run: poetry run pytest --cov=spycular -xr test/ --deselect=test/ws_integration/
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      with:
        file: ./coverage.xml
    - name: Run Numpy Websocket Integration tests
      run: |
        poetry run start_tst_server numpy ws &
        poetry run pytest -x test/ws_integration/numpy_integration
        poetry run stop_tst_server
    - name: Run Torch Websocket Integration tests
      run: |
        poetry run start_tst_server torch ws &
        poetry run pytest  -x test/ws_integration/torch_integration
        poetry run stop_tst_server
